/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-surface-variant": "#464555",
                "secondary-fixed-dim": "#b7c8e1",
                "on-primary-container": "#dad7ff",
                "surface-bright": "#faf8ff",
                "surface-variant": "#dae2fd",
                "on-tertiary-fixed": "#40000c",
                "on-secondary-fixed": "#0b1c30",
                tertiary: "#950029",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#d3e4fe",
                background: "#faf8ff",
                outline: "#777587",
                "on-secondary-container": "#54647a",
                "on-primary-fixed-variant": "#3323cc",
                "surface-container-high": "#e2e7ff",
                "surface-container-low": "#f2f3ff",
                "tertiary-fixed": "#ffdada",
                primary: "#3525cd",
                "on-error": "#ffffff",
                "primary-fixed": "#e2dfff",
                "error-container": "#ffdad6",
                "inverse-primary": "#c3c0ff",
                "surface-container": "#eaedff",
                "outline-variant": "#c7c4d8",
                "inverse-surface": "#283044",
                "tertiary-container": "#c20038",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                surface: "#faf8ff",
                "surface-tint": "#4d44e3",
                "primary-fixed-dim": "#c3c0ff",
                "surface-dim": "#d2d9f4",
                "inverse-on-surface": "#eef0ff",
                "surface-container-highest": "#dae2fd",
                "secondary-container": "#d0e1fb",
                "on-tertiary-container": "#ffd0d2",
                "on-secondary-fixed-variant": "#38485d",
                "on-tertiary-fixed-variant": "#920028",
                "on-background": "#131b2e",
                "on-primary": "#ffffff",
                secondary: "#505f76",
                "primary-container": "#4f46e5",
                "on-primary-fixed": "#0f0069",
                "on-tertiary": "#ffffff",
                error: "#ba1a1a",
                "on-surface": "#131b2e",
                "tertiary-fixed-dim": "#ffb3b6",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            fontFamily: {
                headline: ["Manrope", "sans-serif"],
                body: ["Inter", "sans-serif"],
                label: ["Inter", "sans-serif"],
                display: ["Manrope", "sans-serif"],
            },
        },
    },
    plugins: [],
};
